matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-6 && export CXX=g++-6"
      before_install:
      - eval ${MATRIX_EVAL}
      python: 2.7

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-6 && export CXX=g++-6"
      before_install:
      - eval ${MATRIX_EVAL}
      python: 3.5

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - texlive-full
            - graphviz
      env:
        - MATRIX_EVAL="export CC=gcc-6 && export CXX=g++-6"
      python: 3.6
      before_install:
      - eval ${MATRIX_EVAL}

    - os: osx
      osx_image: xcode8

language: python

install:
  - export PATH=${TRAVIS_BUILD_DIR}/dist_install/bin:$PATH
  - export SECDEC_CONTRIB=${TRAVIS_BUILD_DIR}/dist_install/
  - export PYTHONPATH=${TRAVIS_BUILD_DIR}/dist_install/pySecDec_install:$PYTHONPATH
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt --only-binary=numpy
  - make dist
  - mv pySecDec-*/ dist_install
  - cd dist_install
  - make
  - mv pySecDec-*/ pySecDec_install/
  - wget https://www.normaliz.uni-osnabrueck.de/wp-content/uploads/2016/04/Normaliz3.1.1Linux64.zip --no-check-certificate
  - unzip Normaliz3.1.1Linux64.zip
  - mv Normaliz3.1/normaliz bin/normaliz
  - mv Normaliz3.1/nmzIntegrate bin/nmzIntegrate
  - cd ..

script: 
  - nosetests
  - make util-check
  - make doctest
